[
    {
        "cause": {
            "name": "ConnectTimeoutError",
            "code": "UND_ERR_CONNECT_TIMEOUT",
            "message": "Connect Timeout Error"
        },
        "idProceso": 80553011,
        "iOfA": "0-113"
    }
]
